FROM golang:1.23-alpine3.20

EXPOSE 40000
EXPOSE 8000

WORKDIR /app

RUN apk --no-cache add protobuf protobuf-dev

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/cortesi/modd/cmd/modd@latest

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1

RUN go install github.com/vektra/mockery/v2@v2.43.2

CMD ["sh", "-c", "modd -fdev/modd.conf"]
